### ISSUE TITLE
internal error by opening ticket

### ISSUE THREAD

**Issue by u2mike** [anjlab/redmine_inline_note_images_plugin#6]
my redmine version: 2.0.3.stable

i installed this plugin ...

after restarting apache i can not open tickets with images (not deleted images!).
i get errormessage: (mozilla browser)
--- cut log browser ---
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
--- cut log browser ---

after restarting redmine i can acces to the ticket.

thx to all in advance!

here logfile:
--- cut ------
1303215955_69839984765880 at /opt/bitnami/apps/redmine/htdocs/app/views/attachments/_links.html.erb:11)
  Rendered attachments/_links.html.erb (10.1ms)
  Rendered issue_relations/_form.html.erb (3.7ms)
  Rendered issues/_relations.html.erb (6.3ms)
  Rendered issues/_history.html.erb (7.5ms)
  Rendered issues/show.html.erb within layouts/base (229.2ms)
Completed 500 Internal Server Error in 663ms

ActionView::Template::Error (Missing partial hooks/inline_image_hook/inline_images_paste with {:formats=>[:html], :handlers=>[:rjs, :builder, :erb, :rsb], :locale=>[:de, :en]}. Searched in:
- "/opt/bitnami/apps/redmine/htdocs/plugins/redmine_close_button/app/views"
- "/opt/bitnami/apps/redmine/htdocs/app/views"
  ):
  15:     <% end %>
  16:     <%= render_notes(issue, journal, :reply_links => reply_links) unless journal.notes.blank? %>
  17:   </div>
  18:   <%= call_hook(:view_issues_history_journal_bottom, { :journal => journal }) %>
  19: <% end %>
  20:
  21: <% heads_for_wiki_formatter if User.current.allowed_to?(:edit_issue_notes, issue.project) || User.current.allowed_to?(:edit_own_issue_notes, issue.project) %>
  lib/redmine/hook.rb:111:in `send'
  lib/redmine/hook.rb:111:in`view_issues_history_journal_bottom'
  lib/redmine/hook.rb:61:in `send'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_history.html.erb:18:in`_app_views_issues__history_html_erb___1159529660_69839986091480'
  app/views/issues/_history.html.erb:2:in `each'
  app/views/issues/_history.html.erb:2:in`_app_views_issues__history_html_erb___1159529660_69839986091480'
  app/views/issues/show.html.erb:117:in `_app_views_issues_show_html_erb__526621228_69839986678780'
  app/controllers/issues_controller.rb:118:in`show'
  app/controllers/issues_controller.rb:115:in `show'
  --- cut ---

If you are the Redmine administrator, check your log files for details about the error.

**Comment by serggl** [comment]
What is the redmine/ruby version?

**Comment by u2mike** [comment]
Redmine version                          2.0.3.stable
  Ruby version                             1.8.7 (x86_64-linux)
  Rails version                            3.2.6
  Environment                              production
  Database adapter                         MySQL

**Comment by serggl** [comment]
@u2mike can you please check the newes plugin version?

**Comment by u2mike** [comment]
@serggl 
i installed the newest plugin version ... with migration ...
after updating (with email) an issue with image  i get the following error by loading the issue

Page not found
The page you were trying to access doesn't exist or has been removed.
here is the logfile:

####### cut-start ###########
Started GET "/redmine/issues/11" for 10.205.10.1 at Tue Jun 04 20:48:37 +0000 2013
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"11"}
DEPRECATION WARNING: :confirm option is deprecated and will be removed from Rails 4.0. Use ':data => { :confirm => 'Text' }' instead. (called from _app_views_issues__action_menu_html_erb__840155932_69862513676720 at /opt/bitnami/apps/redmine/htdocs/app/views/issues/_action_menu.html.erb:6)
  Rendered issues/_action_menu.html.erb (11.1ms)
DEPRECATION WARNING: :confirm option is deprecated and will be removed from Rails 4.0. Use ':data => { :confirm => 'Text' }' instead. (called from _app_views_attachments__links_html_erb___177970698_69862516810600 at /opt/bitnami/apps/redmine/htdocs/app/views/attachments/_links.html.erb:11)
DEPRECATION WARNING: :confirm option is deprecated and will be removed from Rails 4.0. Use ':data => { :confirm => 'Text' }' instead. (called from _app_views_attachments__links_html_erb___177970698_69862516810600 at /opt/bitnami/apps/redmine/htdocs/app/views/attachments/_links.html.erb:11)
DEPRECATION WARNING: :confirm option is deprecated and will be removed from Rails 4.0. Use ':data => { :confirm => 'Text' }' instead. (called from _app_views_attachments__links_html_erb___177970698_69862516810600 at /opt/bitnami/apps/redmine/htdocs/app/views/attachments/_links.html.erb:11)
  Rendered attachments/_links.html.erb (20.1ms)
  Rendered issue_relations/_form.html.erb (3.0ms)
  Rendered issues/_relations.html.erb (5.3ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (2.3ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (2.1ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (2.1ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (2.2ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (2.0ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (2.3ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (2.2ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (195.0ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (4.9ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (4.8ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (4.5ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (4.1ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (4.0ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (3.8ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (2.1ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (2.0ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (2.1ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (1.9ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (7.5ms)
  Rendered issues/_history.html.erb (643.1ms)
  Rendered issues/show.html.erb within layouts/base (713.8ms)
Completed 500 Internal Server Error in 1386ms

ActionController::RoutingError (No route matches {:controller=>"attachments", :action=>"thumbnail", :id=>#<Attachment id: 103, container_id: 11, container_type: "Issue", filename: "image002.jpg", disk_filename: "130604203834_image002.jpg", filesize: 1372, content_type: "image/jpeg", digest: "1fd790f1736992a442d4fa4b2af63e67", downloads: 0, author_id: 4, created_on: "2013-06-04 20:38:34", description: nil>}):
  lib/redmine/hook.rb:111:in `send'
  lib/redmine/hook.rb:111:in`view_issues_history_journal_bottom'
  lib/redmine/hook.rb:61:in `send'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_history.html.erb:18:in`_app_views_issues__history_html_erb___378427871_69862517317940'
  app/views/issues/_history.html.erb:2:in `each'
  app/views/issues/_history.html.erb:2:in`_app_views_issues__history_html_erb___378427871_69862517317940'
  app/views/issues/show.html.erb:117:in `_app_views_issues_show_html_erb___223716890_69862513820840'
  app/controllers/issues_controller.rb:118:in`show'
  app/controllers/issues_controller.rb:115:in `show'

######### cut-end ###########
